### ISSUE TITLE
release checklist

### ISSUE THREAD

**Issue by ltalirz** [lsmo-epfl/aiida-lsmo#7]
We should make a proper release of this repository & register it on the AiiDA registry, so that it becomes more easily findable and that we can reference versions of the repo for workflows used in projects (such as CURATED-COFs).

- [x] I'll make a PR to add travis & readthedocs (fixing #5).
- [x] merge aiida-1.0 into master
- [x] decide where to host this repository - should this be hosted under some lsmo organisation?
- [ ] add tests/examples. we might only want to test parts here; no point in running long workflows on travis
- [x] release calc_pe on pypi and add as dependency here

@danieleongari anything that needs to be done in the workflows before making an alpha release?

**Comment by danieleongari** [comment]
I'm doing some heavy development on it, I will plan to make a PR for everything by the end of the week.

**Comment by ltalirz** [comment]
great. as for the location of the repo, I guess it should go here:
https://github.com/lsmo-epfl

**Comment by ltalirz** [comment]
@danieleongari just to remember: it seems `calc_pe` is not installed 
https://travis-ci.org/ltalirz/aiida-lsmo/jobs/610826175

**Comment by danieleongari** [comment]
Regarding the host of the repository,
I would opt to put it on lsmo-epfl since we already moved there aiida-lsmo-setup and aiida-lsmo-codes. 
Please @yakutovicha proceed with the transfer if we all agree on that.

**Comment by yakutovicha** [comment]
> Please @yakutovicha proceed with the transfer if we all agree on that.
done

**Comment by danieleongari** [comment]
checklist done except for tests that are not a priority: there is anyway an issue open for that.
